apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      containers:
        - name: app
          image: courselabs/queue-worker:6.0
          volumeMounts:
            - name: config
              mountPath: "/app/appsettings.json"
              subPath: appsettings.json
              readOnly: true
            - name: cache
              mountPath: "/mnt/cache"
            - name: database
              mountPath: "/mnt/database"
      volumes:
        - name: config
          configMap:
            name:  config-queue-worker
        - name: cache
          emptyDir: {}
        - name: database
          persistentVolumeClaim:
            claimName: pvc-azurefile
            
